/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.commons.math3.stat.descriptive.DescriptiveStatistics;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        DescriptiveStatistics descriptiveStatistics = new DescriptiveStatistics(); // import 의존성 잘 되는지 확인
        System.out.println(descriptiveStatistics.getN());
    }
}
